// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBteJZoirarB77b3Cgo67njG6meoGNq_U',
    appId: '1:826004672204:web:4352aaeba03118fb68fc69',
    messagingSenderId: '826004672204',
    projectId: 'ascon-alumni-91df2',
    authDomain: 'ascon-alumni-91df2.firebaseapp.com',
    storageBucket: 'ascon-alumni-91df2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRAHs28jft1xID0OYcTM6_pNfx60BTyZM',
    appId: '1:826004672204:android:3ad87496f37b496f68fc69',
    messagingSenderId: '826004672204',
    projectId: 'ascon-alumni-91df2',
    storageBucket: 'ascon-alumni-91df2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKK1Pdc1P-GNX4SzhPA9pPNrF1wka7BmM',
    appId: '1:826004672204:ios:0a468a0bdec47e1968fc69',
    messagingSenderId: '826004672204',
    projectId: 'ascon-alumni-91df2',
    storageBucket: 'ascon-alumni-91df2.firebasestorage.app',
    iosBundleId: 'com.example.asconMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKK1Pdc1P-GNX4SzhPA9pPNrF1wka7BmM',
    appId: '1:826004672204:ios:0a468a0bdec47e1968fc69',
    messagingSenderId: '826004672204',
    projectId: 'ascon-alumni-91df2',
    storageBucket: 'ascon-alumni-91df2.firebasestorage.app',
    iosBundleId: 'com.example.asconMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY4zVcmp24FgS1crn-K3TrcK6tdzzJsVQ',
    appId: '1:826004672204:web:556bcc22d852561368fc69',
    messagingSenderId: '826004672204',
    projectId: 'ascon-alumni-91df2',
    authDomain: 'ascon-alumni-91df2.firebaseapp.com',
    storageBucket: 'ascon-alumni-91df2.firebasestorage.app',
  );
}
